- name:     Playbook para demostraci贸n de uso de Ansible Async
  hosts:    all

  tasks:
    - name: M贸dulo Command
      command: 'sleep 15'
      async: 60
      poll: 0
      register: estado_async

    - name: M贸dulo Ping
      ping: ''

    - name: M贸dulo Debug
      debug:
        msg: 'Otra tarea'

    - name: Consultar el estado
      async_status:
        jid: '{{ estado_async.ansible_job_id }}'
      register: estado
      until: estado.finished
      retries: 30